# Generated by Django 5.2.1 on 2025-07-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_customuser_updated_at_alter_customuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
